# Autogenerated wrapper script for AOCL_jll for x86_64-linux-gnu-cxx03
export aocl_blas_ilp64, aocl_lapack_ilp64, aocl_utils

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("AOCL")
JLLWrappers.@declare_library_product(aocl_blas_ilp64, "libblis-mt.so.5")
JLLWrappers.@declare_library_product(aocl_lapack_ilp64, "libflame.so")
JLLWrappers.@declare_library_product(aocl_utils, "libaoclutils.so")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        aocl_blas_ilp64,
        "lib/libblis-mt.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        aocl_lapack_ilp64,
        "lib/libflame.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        aocl_utils,
        "lib/libaoclutils.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
